name: 'Enhanced PR labeler Action'
description: 'Label Pull Requests based on configurable rules'
author: 'Jaeyeon Kim <anencore94@gmail.com>'
inputs: 
  config_path:
    description: 'Path for labeling rules'
    required: false
    default: '.github/labeler.yml'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: tag
  color: green
