name: Label PRs

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: anencore94/labeler@v1.0.5
        with:
          config_path: ".github/labeler.yml"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
